server:
  port: 8181
  servlet:
    context-path: /api
spring:
  application:
    name: demo-saas-platform
  flyway:
    enabled: true
  jpa:
    show-sql: true

logging:
  pattern:
    level: "%5p [${spring.application.name:}] tenantId=%X{tenantId:-}"
